TimeTableManagement/TimeTableManagement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("timetable.urls")),
]

TimeTableManagement/timetable/urls.py
from django.urls import path
from timetable import views
app_name='timetable'
urlpatterns = [
    path("home",views.Homepg.as_view(),name='home'),
    path("",views.CreateTable,name='create'),
    path("ajax/getdrop",views.get_room,name='getdrop'),
    path("timetable",views.ViewTimeTable.as_view(),name='view'),
    path("form",views.get_form,name='form'),
    path("endsession",views.endsession,name='end'),
]

TimeTableManagement/timetable/models.py
from django.db import models
from datetime import datetime,timedelta
# Create your models here.
class Course(models.Model):
    Course_Name=models.CharField(max_length=256,unique=True)
    def __str__(self):
        return self.Course_Name
class Batch(models.Model):
    Batch_Code=models.CharField(max_length=256,unique=True)
    Course=models.ForeignKey(Course,on_delete=models.CASCADE)
    Starting_Date=models.DateField()
    Fees=models.IntegerField()
    Active_Status=models.IntegerField(default=1)
    def __str__(self):
        return self.Batch_Code
class ClassRoom(models.Model):
    Class_Name=models.CharField(max_length=256,unique=True)
    No_of_Students=models.IntegerField()
    def __str__(self):
        return self.Class_Name
def next_day():
    return datetime.now() + timedelta(days=1)
class TimeTable(models.Model):
    Select_Batch=models.ForeignKey(Batch,on_delete=models.CASCADE)
    Start_Time = models.TimeField(default=datetime.now)
    End_Time = models.TimeField()
    Class_Room=models.ForeignKey(ClassRoom,on_delete=models.CASCADE)
    Date=models.DateField(default=next_day)

TimeTableManagement/timetable/forms.py
from django.forms import ModelForm
from timetable.models import TimeTable,Batch,ClassRoom

class TableForm(ModelForm):
    class Meta:
        model= TimeTable
        exclude= ('Date',)
    def __init__(self,batchcode, *args, **kwargs):
        super(TableForm,self).__init__(*args, **kwargs)
        if(batchcode):
            obj = Batch.objects.all()
            for i in batchcode:
                obj=obj.exclude(Batch_Code=i)
            self.fields['Select_Batch'].queryset =obj
        self.fields['Class_Room'].queryset =ClassRoom.objects.none()

TimeTableManagement/timetable/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView,ListView
# Create your views here.
from timetable.models import Batch,ClassRoom,TimeTable
from timetable.forms import TableForm
from django.contrib import messages
from django.contrib.messages import get_messages
lst=[]
ro={}
re={}
class Homepg(TemplateView):
    template_name = 'base.html'
def get_room(request):
    global ro
    global re
    st=request.GET.get('Start_Time')
    en=request.GET.get('End_Time')
    print("st",st,"end",en)
    cls=ClassRoom.objects.all()
    if st not in ro or en not in re:
        for i,j in zip(ro,re):
            if((st>i and st<j) or (en>i and en<j)):
                print("------------------------error---------------------------")
                messages.warning(request, 'Error:Time Added Conflicts with Existing Schedule')
        else:
            cls = ClassRoom.objects.all()
            return render(request, 'timetable/getdrop.html', {'cls': cls})
    else:
        if(ro[st]==re[en]):
            for k in range(0,len(ro[st])):
                cls=cls.exclude(Class_Name=ro[st][k])
            return render(request, 'timetable/getdrop.html', {'cls': cls})
    return render(request,'timetable/getdrop.html', {'cls':cls})
def get_form(request):
    global lst
    frm = TableForm(lst)
    dit = {"form": frm}
    return render(request, "timetable/index.html", dit)
def CreateTable(request):
    frm=TableForm(None)
    global lst
    global ro
    global re
    dit={"form":frm}
    if request.method=='POST':
        storage = get_messages(request)
        mydit=dict(request.POST)
        if(not storage):
            bc=Batch.objects.get(pk=mydit["Select_Batch"][0])
            ts=mydit['Start_Time'][0]
            en=mydit['End_Time'][0]
            cls=ClassRoom.objects.get(pk=mydit['Class_Room'][0])
            fm=TimeTable(Select_Batch=bc,Start_Time=ts,End_Time=en,Class_Room=cls)
            fm.save()
            if ts not in ro:
                ro.update({ts:[cls]})
            else:
                cl=ro[ts]
                cl.append(cls)
                ro[ts]=cl
            if en not in re:
                re.update({en:[cls]})
            else:
                cl=re[en]
                cl.append(cls)
                re[en]=cl
            print("ro",ro,"re",re)
            if(bc not in lst):
                lst.append(bc)
                return get_form(request)
        return get_form(request)
    return render(request,"timetable/index.html",dit)
class ViewTimeTable(ListView):
    model = TimeTable
    context_object_name = 'records'
    template_name = 'timetable/timetable.html'
def endsession(request):
    TimeTable.objects.all().delete()
    global ro
    global lst
    global re
    lst=[]
    ro={}
    re={}
    return render(request,'base.html')

TimeTableManagement/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BASE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">TIMETABLE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <a class="nav-item nav-link" href="{%url 'timetable:create'%}">Add Tables</a>
        <a class="nav-item nav-link " href="{%url 'timetable:view'%}">View Table</a>
        <a class="nav-item nav-link" href="{%url 'timetable:end'%}">End Session</a>
    </div>
  </div>
</nav>
<div class="jumbotron">
{%block body_block%}

{%endblock%}
</div>
</body>
</html>

TimeTableManagement/timetable/templates/timetable/getdrop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Get Drop</title>
</head>
<body>
<option value="">---------</option>
{% for i in cls %}
<option value="{{ i.pk }}">{{ i.Class_Name }}</option>
{% endfor %}
</body>
</html>

TimeTableManagement/timetable/templates/timetable/index.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%block body_block%}
<form method="post" id="NewUser" data-cls-url="{% url 'timetable:getdrop' %}">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div style="margin:20px;text-align:center;">
<a class="btn btn-success" href="{%url 'timetable:view'%}" role="button">View Table</a>
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
  $("#id_Start_Time").change(function () {
      var url = $("#NewUser").attr("data-cls-url");
      var Start_TimeId = $(this).val();
    $("#id_End_Time").change(function () {
      var url = $("#NewUser").attr("data-cls-url");
      var End_TimeId = $(this).val();
       $.ajax({
        url: url,
        data: {
          'Start_Time': Start_TimeId,
          'End_Time': End_TimeId
        },
        success: function (data) {
          $("#id_Class_Room").html(data);
        }
      });
    });
     });
  </script>
{%endblock%}

TimeTableManagement/timetable/templates/timetable/timetable.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%block body_block%}
<table class="table table-dark">
  <thead>
    <tr>
        <th scope="col">DATE</th>
        <th scope="col">BATCH CODE</th>
        <th scope="col">STARTING TIME</th>
        <th scope="col">END TIME</th>
        <th scope="col">CLASS ROOM</th>
    </tr>
  </thead>
  <tbody>
{%for i in records%}
<tr>
    <td scope="col">{{i.Date}}</td>
    <td scope="col">{{i.Select_Batch}}</td>
    <td scope="col">{{i.Start_Time}}</td>
    <td scope="col">{{i.End_Time}}</td>
    <td scope="col">{{i.Class_Room}}</td>

</tr>
{%endfor%}
  </tbody>
</table>
<a class="btn btn-danger" href="{%url 'timetable:end'%}" role="button">End Session</a>
{%endblock%}